project:
  type: website
  output-dir: docs

website:
  title: "LAB 2"
  navbar:
    left:
      - index.qmd
      - dummy1.qmd
      - dummy2.qmd
      - dummy3.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

